name: Build
'on':
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: 5df52eb8-e4b1-4a3a-bd1c-cbbc66c69bd1
          SONAR_TOKEN: 6c6b2469c3347bcc5a90cd7dbec5c8ce8a816eb6
          args: >-
            -Dsonar.projectKey=examly-test_5df52eb8-e4b1-4a3a-bd1c-cbbc66c69bd1
            -Dsonar.organization=examly-test -Dsonar.sources=
            -Dsonar.verbose=true
